### ISSUE TITLE
Add forum or GitHub discussions

### ISSUE THREAD

**Issue by InAnYan** [jeremychone/rust-genai#30]
### Bug description

Hi! It seems the only way to contact you, or ask for questions, or make feature requests is to use this bug template. But it's certainly not a bug

**Comment by jeremychone** [comment]
@InAnYan

Very good point. The GitHub issue templates need updating; I’ll take care of that.

I’ll add more types of GitHub issue templates (or remove them as needed).

Also, good suggestion on the discussion; I’ve just started it: https://github.com/jeremychone/rust-genai/discussions

**Comment by InAnYan** [comment]
As the "discussions" is opened, I will close the issue.

Thanks!
